# Generated by Django 2.2.6 on 2019-11-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appIW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cordillera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='provincia',
        ),
        migrations.AddField(
            model_name='estacion',
            name='abierta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='enlacePagina',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='estacion',
            name='nKilometrosTotales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='estacion',
            name='nPistasTotales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pista',
            name='abierta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nKilometros',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nPistas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pista',
            name='dificultad',
            field=models.CharField(default='Verde', max_length=10),
        ),
        migrations.AlterField(
            model_name='pista',
            name='estacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appIW.Estacion'),
        ),
        migrations.AlterField(
            model_name='pista',
            name='longitud',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pista',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.AddField(
            model_name='estacion',
            name='cordillera',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appIW.Cordillera'),
        ),
    ]
