# Generated by Django 2.2.6 on 2019-11-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cordillera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abierta', models.BooleanField()),
                ('nPistas', models.IntegerField()),
                ('nPistasTotales', models.IntegerField()),
                ('nKilometros', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nKilometrosTotales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('enlacePagina', models.CharField(max_length=200)),
                ('cordillera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIW.Cordillera')),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abierta', models.BooleanField()),
                ('dificultad', models.CharField(max_length=10)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIW.Estacion')),
            ],
        ),
    ]
