# Generated by Django 2.2.6 on 2019-11-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appIW', '0002_auto_20191113_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cordillera',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='abierta',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='cordillera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIW.Cordillera'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='enlacePagina',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nKilometros',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nKilometrosTotales',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nPistas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nPistasTotales',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pista',
            name='abierta',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pista',
            name='dificultad',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pista',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appIW.Estacion'),
        ),
        migrations.AlterField(
            model_name='pista',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
